begin;

-- =========================================================
-- OCTOSON MULTIPLAYER FOUNDATION
-- =========================================================

create table if not exists public.game_rooms (
  id uuid primary key default gen_random_uuid(),

  -- Short shareable code: /play/ABC123
  code text not null unique,

  -- reaction, connect4, blackjack, etc.
  game text not null default 'lobby',

  host_id text not null,

  -- waiting | playing | finished | closed
  status text not null default 'waiting',

  -- private room settings / game-specific options
  settings jsonb not null default '{}'::jsonb,

  max_players integer not null default 8,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint game_rooms_code_format
    check (code ~ '^[A-Z0-9]{6}$'),

  constraint game_rooms_max_players
    check (max_players between 2 and 20),

  constraint game_rooms_status
    check (
      status in (
        'waiting',
        'playing',
        'finished',
        'closed'
      )
    )
);

create index if not exists game_rooms_host_idx
  on public.game_rooms (host_id);

create index if not exists game_rooms_status_idx
  on public.game_rooms (status);

create index if not exists game_rooms_created_idx
  on public.game_rooms (created_at desc);


-- =========================================================
-- PLAYERS INSIDE ROOMS
-- =========================================================

create table if not exists public.game_room_players (
  id uuid primary key default gen_random_uuid(),

  room_id uuid not null
    references public.game_rooms(id)
    on delete cascade,

  user_id text not null,

  ready boolean not null default false,

  seat integer,

  score bigint not null default 0,

  -- Useful later for avatars/name snapshots/game metadata
  player_data jsonb not null default '{}'::jsonb,

  joined_at timestamptz not null default now(),
  last_seen timestamptz not null default now(),

  unique (room_id, user_id),

  constraint game_room_player_seat
    check (seat is null or seat >= 0)
);

create index if not exists game_room_players_room_idx
  on public.game_room_players (room_id);

create index if not exists game_room_players_user_idx
  on public.game_room_players (user_id);


-- =========================================================
-- MATCHES
-- A room may eventually contain multiple rounds/rematches.
-- =========================================================

create table if not exists public.game_matches (
  id uuid primary key default gen_random_uuid(),

  room_id uuid not null
    references public.game_rooms(id)
    on delete cascade,

  game text not null,

  status text not null default 'waiting',

  state jsonb not null default '{}'::jsonb,

  winner_id text,

  started_at timestamptz,
  ended_at timestamptz,

  created_at timestamptz not null default now(),

  constraint game_matches_status
    check (
      status in (
        'waiting',
        'playing',
        'finished',
        'cancelled'
      )
    )
);

create index if not exists game_matches_room_idx
  on public.game_matches (room_id);

create index if not exists game_matches_created_idx
  on public.game_matches (created_at desc);


-- =========================================================
-- GAME EVENTS
-- Later:
-- reaction clicks
-- connect 4 moves
-- blackjack actions
-- chat/reactions
-- etc.
-- =========================================================

create table if not exists public.game_events (
  id bigint generated by default as identity primary key,

  match_id uuid not null
    references public.game_matches(id)
    on delete cascade,

  user_id text,

  event_type text not null,

  payload jsonb not null default '{}'::jsonb,

  created_at timestamptz not null default now()
);

create index if not exists game_events_match_idx
  on public.game_events (match_id, id);


-- =========================================================
-- AUTOMATIC updated_at
-- =========================================================

create or replace function public.touch_game_room_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists game_rooms_touch_updated_at
  on public.game_rooms;

create trigger game_rooms_touch_updated_at
before update on public.game_rooms
for each row
execute function public.touch_game_room_updated_at();


-- =========================================================
-- REALTIME
-- Ignore duplicate-object errors if tables were previously
-- added to the publication.
-- =========================================================

do $$
begin
  alter publication supabase_realtime
    add table public.game_rooms;
exception
  when duplicate_object then null;
end;
$$;

do $$
begin
  alter publication supabase_realtime
    add table public.game_room_players;
exception
  when duplicate_object then null;
end;
$$;

do $$
begin
  alter publication supabase_realtime
    add table public.game_matches;
exception
  when duplicate_object then null;
end;
$$;

do $$
begin
  alter publication supabase_realtime
    add table public.game_events;
exception
  when duplicate_object then null;
end;
$$;

commit;
